# -*- coding: utf-8 -*-
"""EvidenciaFinal_a01702927

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RIO7KlqfctutA1IHXxIyAG93JUjqQtUP

#Evidencia final UF6

Amiarany Rodríguez | A01702927
"""

import streamlit as st
import pandas as pd
import numpy as np
import ploty as px
import ploty.figure_factory as ff
from bokeh.plotting import figure
import matplotlib.pyplot as plt

st.header(':blue[Police Incident Reports from 2018 to 2020 in San Francisco] :police_car: :us:')
df=pd.read_csv("https://drive.google.com/file/d/11oLcKiW8SgCOp3tGiQCYuRG7pLL_J-Zf/view?usp=share_link/Police_Department_Incident_Reports__2018_to_Present.csv")

st.markdown("_The data shown below belongs to incident reports in the city of San Francisco, from the year 2018 to 2020, with details from each case such as date, day of the week, police district, neighborhood in which it happened, type of incident in category and subcategory, exact location and resolution._")

mapa=pd.DataFRame()
mapa['Date']=df["Incident Date"]
mapa['Day']=df["Incident Day of Week"]
mapa['Neighborhood']=df["Analysis Neighborhood"]
mapa['Incident Category']=df["Incident Category"]
mapa['Incident Subcategory']=df["Incident Subcategory"]
mapa['Resolution']=df["Resolution"]
mapa['lat']=df["Latitude"]
mapa['lon']=df["Longitude"]

mapa=mapa.dropna()
st.map(mapa)

st.write(f'Total Records: {len(df)}')
